name: test
channels:
  - conda-forge
  - omnia

dependencies:
    # Base depends
  - openff-toolkit

    # Removed until a new release which targets openff-toolkit is made.
#  - openmmforcefields
  - openmm
  - pytest
  - nbval
