name: openforcefield
channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    # readthedocs dependencies
    - numpydoc
    - nbsphinx
    - myst-parser>=0.14
    - testpath==0.3.1
    - docutils
    # conda build dependencies
    - python
    - setuptools
    - numpy
    - openmm
    - networkx
    - parmed
    - rdkit
    - ambertools
    - packaging
    # Serialization: Should these be optional?
    - toml
    - bson
    - msgpack-python
    - xmltodict
    - pyyaml
    - cairo >=1.16
    # Theme
    - pip:
        - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
