name: py36

on:
  push:
    branches:
      - 'master'
  schedule:
    # run every monday
    - cron: '0 0 * * 1'

jobs:
  timebomb:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Python 3.6 timebomb
        shell: python
        run: |
          from datetime import date
          assert date(2022, 2, 1) > date.today(), 'Python 3.6 EOL reminder!'
          print("The maintainer of a downstream project has requested that "
                "we maintain py36 compatibility until at least Feb 2022."
                "Contact Jeff Wagner or Yutong Zhao if this is an issue.")